### ISSUE TITLE
Select tags seem to have a double arrow because of the .custom-control and .form-control class

### ISSUE THREAD

**Issue by dinatih** [comfy/comfy-bootstrap-form#11]
Remove the .form-control (or maybe the custom-control because I do not see the difference with the default) from the select tags should fix it.

![screen shot 2018-07-02 at 18 17 20](https://user-images.githubusercontent.com/309161/42175737-cad88ffc-7e26-11e8-8e69-7bba4b78428a.png)
![screen shot 2018-07-02 at 17 48 57](https://user-images.githubusercontent.com/309161/42175738-caed6df0-7e26-11e8-9351-e2e993e33857.png)

Related to https://github.com/comfy/comfortable-mexican-sofa/commit/70011e47674a702d3a3048f8286486e452aa850b#commitcomment-29569101

**Comment by GBH** [comment]
I'm guessing it's in Chrome as I didn't notice it in Firefox. Feel free to make a PR that fixes it. I might find time later this week for this, otherwise.

**Comment by dinatih** [comment]
Yes, in Chrome. I will try to push a P.R. But following the bootstrap doc, the .form-control is not use when using the custom-form class.

https://getbootstrap.com/docs/4.0/components/forms/#select-menu
![screen shot 2018-07-02 at 18 48 39](https://user-images.githubusercontent.com/309161/42176267-b1fe297c-7e28-11e8-8e1a-e66038a63251.png)

**Comment by GBH** [comment]
Hey, what bootstrap version are you using. I checked with 4.1 and 4.1.2 and everything seems to be good. Maybe it was the 4.0 issue? Here's what I see in Chrome (and Firefox)

<img width="516" alt="screen shot 2018-07-22 at 8 33 53 am" src="https://user-images.githubusercontent.com/78363/43045638-624c200c-8d8a-11e8-87a2-73ffd08147c9.png">

**Comment by dinatih** [comment]
Hi, 
I am on bootstrap 4.1.1., and mac OS High Sierra 10.13.6. Here a screenshot on safari chrome and firefox 
![screen shot 2018-07-23 at 10 43 05](https://user-images.githubusercontent.com/309161/43066762-cc2ad15e-8e65-11e8-9c14-915456768dc5.png)

**Comment by GBH** [comment]
How odd. Can you spin up https://github.com/comfy/comfy-bootstrap-form/tree/master/demo and check if you also seeing the same thing there? Thanks.

**Comment by dinatih** [comment]
Alright, I got it, it show well on your demo app, the difference is in custom-select class, that use only `    appearance: none` in my app and not `-webkit-appearance: none;   -**-appearance: none;     appearance: none;` It seems that on chrome `appearance: none` is not recognized yet. But in the codebase of bootstrap I can see that they only declare `appearance: none` that is convert (I do not see how) to `-webkit-**`. But not in my app where it is just `appearance: none`  
![screen shot 2018-07-23 at 15 43 27](https://user-images.githubusercontent.com/309161/43080408-f94b08fa-8e8f-11e8-9fd1-5d87e3d6ab62.png)
![screen shot 2018-07-23 at 15 43 53](https://user-images.githubusercontent.com/309161/43080416-fc6222bc-8e8f-11e8-9a34-a933cfa2948d.png)

And on my app 
![screen shot 2018-07-23 at 15 51 33](https://user-images.githubusercontent.com/309161/43080603-5a87adf8-8e90-11e8-8810-54f8323adc33.png)

We did not have overridden any of the cms scss file, so I do not understand. 
As I am  the only with this problem, I think we can close this issue

Thanks for you help

**Comment by GBH** [comment]
Are you using `autoprefixer-rails` gem? It automatically fills in browser-specific css rules. `appearance: none` will be expanded to target all browser.

**Comment by dinatih** [comment]
No, I do not use it but if I add it to the project, everything works well, as in your demo. But I do not see this dependance in you demo app, so it is weird

**Comment by GBH** [comment]
🤷‍♂️ I'll close this as it seems to be more of a CSS issue than generated markup.

**Comment by Songchb** [comment]
I had the exactly same problem and got help from this page.
thx :D
