### ISSUE TITLE
Demo site doesn't work due to missing tables

### ISSUE THREAD

**Issue by morgant** [comfy/comfy-bootstrap-form#22]
I'm not sure if this is new with Rails 6, but when I try to load https://localhost:3000/ after running the following, I get a "ActiveRecord::StatementInvalid in BootstrapController#form. Could not find table 'users'" error:

```
bundle
cd demo
./bin/rails db:setup
./bin/rails s
```

**Comment by morgant** [comment]
It appears that the following line was removed from `demo/README.md` in commit [7e48d5afef88fd5b70a7ef29070592ee481246d0](https://github.com/comfy/comfy-bootstrap-form/commit/7e48d5afef88fd5b70a7ef29070592ee481246d0#diff-709384f5c992b1e62ed4d43183640edc):

```
bundle exec rails db:schema:load
```

The instructions in `demo/README.md` should probably read as follows:

```
bundle
cd demo
./bin/rails db:schema:load
./bin/rails s
```

**Comment by GBH** [comment]
Yeap. I adjusted readme. Thanks.

**Comment by morgant** [comment]
Thanks! My apologies for not just submitting a PR for that.
