### ISSUE TITLE
`label` should support the `for` option for the correct association with the inputs

### ISSUE THREAD

**Issue by glebm** [comfy/comfy-bootstrap-form#8]
This is giving me a headache when trying to write an system test that follows best practices (selecting inputs by label text)

**Comment by glebm** [comment]
`for` doesn't work here:

```ruby
      form_group bootstrap: { label: { text: label, for: tag_input_id, class: "renderable-#{renderable}" } } do
```

**Comment by GBH** [comment]
It's fixed in recent commits. I'll release new version shortly.

**Comment by GBH** [comment]
4.0.2 is released. Fixed this issue and bunch of others.
