### ISSUE TITLE
Support custom control on select

### ISSUE THREAD

**Issue by KevinSjoberg** [comfy/comfy-bootstrap-form#9]
I know we have the `custom_control` option to opt out from native components. Unfortunately it does not work with `select` currently. See https://getbootstrap.com/docs/4.0/components/forms/#select-menu for details.

**Given**

```erb
<%= f.select :foo, [["Bar", :bar], ["Baz", :baz]], bootstrap: { custom_control: true } %>
```

**When**

I check the source code of the generated output.

**Then**

I expect the class `custom-select` to be present on the `<select>`.

**Comment by GBH** [comment]
Closing with #10 merge
